HOMEWORK_NUMBERS:
  - ""
  - "2"
  - "3"
  - "4"
  - "9"
  - "12"
  - "14"
  - "17.1"
  - "17.2"
HOMEWORK_NUMBERS_FLOG_FLAY:
  - "2"
  - "3"
  - "4"
  - "12"
  - "14"
  - "17.1"
  - "17.2"
HOMEWORK_NAMES:
  - "vh_nivo"
  - "class002"
  - "class003"
  - "class004"
  - "class009"
  - "class012"
  - "class014"
  - "class017.1"
  - "class017.2"
DEADLINES:
  - "Sep 17 2014 20:00"
  - "Sep 22 2014 20:00"
  - "Sep 24 2014 20:00"
  - "Sep 29 2014 20:00"
  - "Oct 27 2014 20:00"
  - "Nov 10 2014 20:00"
  - "Nov 13 2014 06:00"
  - "Dec 02 2014 06:00"
  - "Dec 02 2014 06:00"
REGEXES:
  - non
  - ^[a-zA-Z0-9]+_[a-zA-Z0-9]+_Class2_[12].rb$
  - ^[a-zA-Z0-9]+_[a-zA-Z0-9]+_Class3_[12].rb$
  - ^[a-zA-Z0-9]+_[a-zA-Z0-9]+_Class4_[12].rb$
  - non
  - ^[a-zA-Z0-9]+_[a-zA-Z0-9]+_[AB]_\d+.rb$
  - ^[a-zA-Z0-9]+_[a-zA-Z0-9]+_[AB]_\d+.rb$
  - ^[a-zA-Z0-9]+_[a-zA-Z0-9]+_[AB]_\d+.rb$
  - ^[a-zA-Z0-9]+_[a-zA-Z0-9]+_[AB]_\d+.rb$
